const fs = require('fs');
let code = fs.readFileSync('c:/Users/Murilo vieira/Documents/projetos/mestre-ferramentas - V2/src/data/articles.ts', 'utf8');

const replacements = {
  'Ǹ': 'é',
  'ǜ': 'ã',
  'Ǧ': 'ê',
  'ǭ': 'á',
  'ǧ': 'ú',
  'ǽ': 'â',
  '': 'ç',
  'mçveis': 'móveis',
  'Mçveis': 'Móveis',
  'potência': 'potência', // since Ǧ is handled
  'custo-benefçcio': 'custo-benefício',
  'adeus à frustraçǜo': 'adeus à frustração',
  'mçǜo': 'mão',
  'adequada Ǹ': 'adequada é',
  'complicaçes': 'complicações',
  'precisǜo': 'precisão',
  'segurança': 'segurança',
  'pçs-venda': 'pós-venda',
  'çnica': 'única',
  'çnico': 'único',
  'tçcnico': 'técnico',
  'prç-furo': 'pré-furo',
  'sçlida': 'sólida',
  'padrǜo': 'padrão',
  'durçvel': 'durável',
  'lçderes': 'líderes',
  'concluídas': 'concluídas',
  'construçǜo': 'construção',
  'soluçes': 'soluções',
  'çtimo': 'ótimo',
  'projetç-las': 'projetá-las',
  'usç-la': 'usá-la',
  'manutençǜo': 'manutenção',
  'vocǦ': 'você',
  'painǸis': 'painéis',
  'elçtricas': 'elétricas',
  'orçamento': 'orçamento',
  'informaçes': 'informações',
  'çgil': 'ágil',
  'furaçǜo': 'furação',
  'vçrios': 'vários',
  'necessçrias': 'necessárias',
  'prçtico': 'prático',
  'força': 'força',
  'bçsicos': 'básicos',
  'bçsicas': 'básicas',
  'condiçes': 'condições',
  'avaliaçes': 'avaliações',
  'mçquina': 'máquina',
  'mçximas': 'máximas',
  'fçcil': 'fácil',
  'Nçquel': 'Níquel',
  'Íon': 'Íon',
  'Lçtio': 'Lítio',
  'fçsico': 'físico',
  'saçde': 'saúde',
  'cçlulas': 'células',
  'çtil': 'útil',
  'retraçǜo': 'retração',
  'resistência': 'resistência',
  'vçlido': 'válido',
  'metçlicas': 'metálicas',
  'marcençrio': 'marcenário',
  'atravçs': 'através',
  'atuaçǜo': 'atuação',
  'perfeiçǜo': 'perfeição',
  'dçvidas': 'dúvidas',
  'mçnimo': 'mínimo',
  'mçnima': 'mínima',
  'mçximos': 'máximos',
  'fçbrica': 'fábrica',
  'experiência': 'experiência',
  'tçcnica': 'técnica',
  'metçlicos': 'metálicos',
  'perfuraçes': 'perfurações',
  'informaçǜo': 'informação',
  'situaçes': 'situações',
  'opçǜo': 'opção',
  'prçprios': 'próprios',
  'fçrias': 'férias',
  'pçblico': 'público',
  'portçteis': 'portáteis',
  'domçsticos': 'domésticos',
  'elçtrica': 'elétrica',
  'necessçrio': 'necessário',
  'mecçnicos': 'mecânicos',
  'mecçnica': 'mecânica',
  'hidrçulica': 'hidráulica',
  'hidrçulico': 'hidráulico',
  'dçvida': 'dúvida',
  'alçm': 'além',
  'mçximo': 'máximo',
  'nçvel': 'nível',
  'nçveis': 'níveis',
  'lçquido': 'líquido',
  'tçtulo': 'título',
  'opçes': 'opções',
  'çs': 'às',
  'ç ': 'é ',
  'çm': 'ém', // for contém? No, might break
};

for (const [bad, good] of Object.entries(replacements)) {
  code = code.split(bad).join(good);
}

fs.writeFileSync('c:/Users/Murilo vieira/Documents/projetos/mestre-ferramentas - V2/src/data/articles.ts', code, 'utf8');
