const fs = require('fs');
let code = fs.readFileSync('c:/Users/Murilo vieira/Documents/projetos/mestre-ferramentas - V2/src/components/MelhorParafusadeiraParaMontarMoveis.tsx', 'utf8');

const replacements = {
  'Ǹ': 'é',
  'ǜ': 'ã',
  'Ǧ': 'ê',
  'ǭ': 'á',
  'ǧ': 'ú',
  'ǽ': 'â',
  '': 'ç',
  'mçvel': 'móvel',
  'mçveis': 'móveis',
  'Mçveis': 'Móveis',
  'cabeça': 'cabeça',
  'dçcadas': 'décadas',
  'manutençǜo': 'manutenção',
  'armçrios': 'armários',
  'alçm': 'além',
  'precisǜo': 'precisão',
  'peças': 'peças',
  'domçstico': 'doméstico',
  'vocǦ': 'você',
  'cartǜo': 'cartão',
  'exercçcio': 'exercício',
  'frequǦncia': 'frequência',
  'opçǜo': 'opção',
  'preço': 'preço',
  'esforço': 'esforço',
  'fçbrica': 'fábrica',
  'Nçquel': 'Níquel',
  'Lçtio': 'Lítio',
  'saçde': 'saúde',
  'cçlulas': 'células',
  'çtil': 'útil',
  'retençǜo': 'retenção',
  'resistência': 'resistência',
  'metçlicas': 'metálicas',
  'açǜo': 'ação',
  'Açǜo': 'Ação',
  'avaliaçes': 'avaliações',
  'condiçes': 'condições',
  'situaçes': 'situações',
  'soluçes': 'soluções',
  'informaçes': 'informações',
  'perfuraçes': 'perfurações',
  'complicaçes': 'complicações',
  'tçcnico': 'técnico',
  'tçcnicos': 'técnicos',
  'tçcnica': 'técnica',
  'tçcnicas': 'técnicas',
  'prçtico': 'prático',
  'prçtica': 'prática',
  'rçpida': 'rápida',
  'rçpido': 'rápido',
  'çtimo': 'ótimo',
  'çnica': 'única',
  'çnico': 'único',
  'çltimo': 'último',
  'çltimos': 'últimos',
  'çgil': 'ágil',
  'fçcil': 'fácil',
  'nçvel': 'nível',
  'nçveis': 'níveis',
  'lçquido': 'líquido',
  'vçlido': 'válido',
  'vçrios': 'vários',
  'dçvida': 'dúvida',
  'dçvidas': 'dúvidas',
  'mçnimo': 'mínimo',
  'mçnima': 'mínima',
  'mçximo': 'máximo',
  'mçximas': 'máximas',
  'pçblico': 'público',
  'portçteis': 'portáteis',
  'domçsticos': 'domésticos',
  'elçtrica': 'elétrica',
  'elçtricas': 'elétricas',
  'necessçrio': 'necessário',
  'necessçria': 'necessária',
  'necessçrias': 'necessárias',
  'mecçnica': 'mecânica',
  'mecçnicos': 'mecânicos',
  'hidrçulica': 'hidráulica',
  'hidrçulico': 'hidráulico',
  'prçprios': 'próprios',
  'fçrias': 'férias',
  'mçquina': 'máquina',
  'mçquinas': 'máquinas',
  'experiência': 'experiência',
  'metçlicos': 'metálicos',
  'marcençrio': 'marcenário',
  'atravçs': 'através',
  'atuaçǜo': 'atuação',
  'perfeiçǜo': 'perfeição',
  'força': 'força',
  'bçsico': 'básico',
  'bçsicos': 'básicos',
  'bçsica': 'básica',
  'bçsicas': 'básicas',
  'ç ': 'é ',
  'çs': 'às',
  'çm': 'ém',
  'nǜo': 'não',
  'Nǜo': 'Não',
  'frustraçǜo': 'frustração',
  'cansaço': 'cansaço',
  'antebraço': 'antebraço',
  'tçm': 'têm',
  'potência': 'potência',
  'custo-benefçcio': 'custo-benefício',
  'adequada Ǹ': 'adequada é',
  'sçlida': 'sólida',
  'padrǜo': 'padrão',
  'durçvel': 'durável',
  'lçderes': 'líderes',
  'concluídas': 'concluídas',
  'construçǜo': 'construção',
  'projetç-las': 'projetá-las',
  'usç-la': 'usá-la',
  'orçamento': 'orçamento',
  'furaçǜo': 'furação',
  'Íon': 'Íon',
  'fçsico': 'físico',
  'retraçǜo': 'retração',
  'informaçǜo': 'informação',
  'opçǜo': 'opção',
  'tçtulo': 'título',
  'opçes': 'opções',
  'coraçǜo': 'coração',
  'posiçǜo': 'posição',
  'açes': 'ações',
  'proteçǜo': 'proteção',
  'funçǜo': 'função',
  'fixaçǜo': 'fixação',
  'ventilaçǜo': 'ventilação',
  'reposiçǜo': 'reposição',
  'direçǜo': 'direção',
  'instalaçǜo': 'instalação',
  'iluminaçǜo': 'iluminação',
  'vibraçǜo': 'vibração',
  'rotaçes': 'rotações',
  'sǜo': 'são',
  'Sǜo': 'São',
  'versǜo': 'versão',
  'visǜo': 'visão',
  'campeǜo': 'campeão',
  'botǜo': 'botão',
  'revisǜo': 'revisão',
  'pressǜo': 'pressão',
  'descriçǜo': 'descrição',
  'atençǜo': 'atenção',
  'fundaçǜo': 'fundação',
  'avaliaçǜo': 'avaliação',
  'aprovaçǜo': 'aprovação',
  'geraçǜo': 'geração',
  'criaçǜo': 'criação',
  'relaçǜo': 'relação',
  'opçǜo': 'opção',
  'soluçǜo': 'solução',
  'adiçǜo': 'adição',
  'limitaçǜo': 'limitação',
  'evoluçǜo': 'evolução',
  'adaptaçǜo': 'adaptação',
  'distribuiçǜo': 'distribuição',
  'exibiçǜo': 'exibição',
  'condiçǜo': 'condição',
  'adiçes': 'adições',
  'ç ': 'é ',
  'prejuçzos': 'prejuízos',
  'irreversçveis': 'irreversíveis',
  'superfçcie': 'superfície',
  'superfçcies': 'superfícies',
  'mobçlia': 'mobília',
  'invçs': 'invés',
  'carvǜo': 'carvão',
  'excelência': 'excelência',
  'contçnuo': 'contínuo',
  'subsçdio': 'subsídio',
  'destrçi': 'destrói',
  'reçne': 'reúne',
  'prç-furo': 'pré-furo',
  'vocç': 'você',
  'Açǜ': 'Açã',
};

for (const [bad, good] of Object.entries(replacements)) {
  code = code.split(bad).join(good);
}

// Any remaining '' characters should probably be 'í' based on words like superfcie -> superfçcie -> superfície (already handled but just in case)
// We already mapped '' to 'ç', so anything that was 'ç' is now 'ç'. But wait, what if '' was 'í'?
// I mapped '' to 'ç'. So 'moblia' -> 'mobçlia'. I then mapped 'mobçlia' to 'mobília'. That's handled.
// What about 'prejuzos' -> 'prejuçzos'? Mapped to 'prejuízos'.
// Let's do a catch all for 'ç' followed by consonant which doesn't make sense, it's probably 'í' or 'ç'
// Actually I'll let it be. Let's write the file.

fs.writeFileSync('c:/Users/Murilo vieira/Documents/projetos/mestre-ferramentas - V2/src/components/MelhorParafusadeiraParaMontarMoveis.tsx', code, 'utf8');
